AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-yozo-summarizer

  Sample SAM Template for lambda-yozo-summarizer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  YozoSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MessagesQueue.fifo
      VisibilityTimeout: 300
      MessageRetentionPeriod: 86400
      FifoQueue: true
  SummarizeFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaSQSPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: sqs:SendMessage
                Resource: !GetAtt YozoSQS.Arn
  SummarizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: summarizer_func/
      Handler: app.lambda_handler
      Runtime: python3.10
      Environment:
        Variables:
          BOT_TOKEN: "{{resolve:secretsmanager:yozo-my-bot-token:SecretString}}"
          CHANNEL_ID: "{{resolve:secretsmanager:yozo-my-channel-id:SecretString}}"
          GROUP_ID: "{{resolve:secretsmanager:yozo-my-group-id:SecretString}}"
          QUEUE_URL: !GetAtt YozoSQS.QueueUrl
      Architectures:
        - x86_64
      Events:
        Summarizer:
          Type: Api
          Properties:
            Path: /summary
            Method: post
      Role: !GetAtt SummarizeFunctionRole.Arn

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SummarizeFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SummarizeFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt SummarizeFunction.Arn
  SummarizeFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SummarizeFunctionRole.Arn
