AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-yozo-summarizer

  Sample SAM Template for lambda-yozo-summarizer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  YozoSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: MessagesQueue.fifo
      VisibilityTimeout: 300
      MessageRetentionPeriod: 86400
      FifoQueue: true
  SummarizeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: summarizer_func/ #edited here, also edited folder name
      Handler: app.lambda_handler
      Runtime: python3.10
      Environment:
        Variables:
          BOT_TOKEN: "{{resolve:secretsmanager:yozo-my-bot-token:SecretString}}"
          CHANNEL_ID: "{{resolve:secretsmanager:yozo-my-channel-id:SecretString}}"
          GROUP_ID: "{{resolve:secretsmanager:yozo-my-group-id:SecretString}}"
          QUEUE_URL: !GetAtt YozoSQS.Arn
      Architectures:
        - x86_64
      Events:
        Summarizer:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /summary
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SummarizeFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SummarizeFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt SummarizeFunction.Arn
  SummarizeFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt SummarizeFunctionRole.Arn
